services:
#    mrs_controle.example:
#        class: MRS\ControleBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  financas.querynative:
    class: MRS\ControleBundle\Service\FinancasService
    arguments: [@service_container]
    public: true
    tags:
      - { name: ServicoTeste }