mrs_controle:
    resource: "@MRSControleBundle/Resources/config/routing.yml"
    prefix:   /
app_financas:
    resource: "@MRSControleBundle/Controller/"
    type:     annotation
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
logout:
    path: /logout